version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dip
      args:
        gem_user: ${GEM_USER}
        gem_password: ${GEM_PASSWORD}
        DOCKER_RUBY_VERSION: $DOCKER_RUBY_VERSION
      labels:
        com.wallarm-billing-api.ruby.version: $DOCKER_RUBY_VERSION
    environment:
      - SSH_AUTH_SOCK=/ssh/auth/sock
      - BUNDLE_PATH=/bundle/$DOCKER_RUBY_VERSION
      - BUNDLE_CONFIG=/app/.bundle/config
      - TEST_DB_HOST=db
      - TEST_DB_NAME=docker
      - TEST_DB_USERNAME=postgres
    command: bash
    depends_on:
      - db

  db:
    image: postgres:${PG_VERSION}-alpine
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
